In [15]:
from dtw import dtw
from numpy.linalg import norm
import numpy as np

In [5]:
a = [7.344632768,
12.60162602,
6.542056075,
10.7266436,
9.489051095,
3.416856492,
5.974842767,
6.557377049,
11.46245059,
11.27819549,
6.413994169,
6.257521059,
3.771551724,
7.167235495,
9.595959596,
8.461538462,
3.576341128,
4.664723032,
13.67924528,
3.531300161,
6.744487678,
17.26907631,
4.819277108]
b = [10.43478261,
6.756756757,
6.432748538,
14.61988304,
12.24489796,
5.223880597,
7.262569832,
6.470588235,
9.550561798,
13.33333333,
6.355932203,
3.892944039,
1.858736059,
4.819277108,
8.737864078,
7.614213198,
4.174950298,
5.306122449,
13.2231405,
1.826484018,
7.614213198,
14.38848921,
1.724137931]

In [16]:
a = np.array(a).reshape(-1,1)
b = np.array(b).reshape(-1,1)

In [19]:
dist, cost, acc, path = dtw(a, b, norm)

In [23]:
path

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22]))

In [8]:
len(a),len(b)

(23, 23)

In [14]:
array([0, 0, 1, 1, 2, 4, 2, 1, 2, 0]).reshape(-1, 1)

array([[0],
       [0],
       [1],
       [1],
       [2],
       [4],
       [2],
       [1],
       [2],
       [0]])

In [13]:
from numpy import array